-- Drop the table if it exists (be careful with this in production!)
-- DROP TABLE IF EXISTS signals;

-- Create the signals table with proper auto-incrementing ID
CREATE TABLE IF NOT EXISTS signals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id TEXT NOT NULL,
    sender TEXT NOT NULL,
    sender_name TEXT NOT NULL,
    target TEXT,
    type TEXT NOT NULL,
    sdp TEXT,
    candidate TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Enable Row Level Security
ALTER TABLE signals ENABLE ROW LEVEL SECURITY;

-- Create policies
CREATE POLICY "Enable read access for all" 
ON signals FOR SELECT 
USING (true);

CREATE POLICY "Enable insert access for all" 
ON signals FOR INSERT 
WITH CHECK (true);

-- Grant access to anon role
GRANT ALL ON TABLE signals TO anon;